# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Ubuntu 14.04 (Trusty Thar)
  config.vm.define "senaite-trusty" do |app|
    app.vm.hostname = "senaite"
    # https://app.vagrantup.com/ubuntu/boxes/trusty64
    app.vm.box = "ubuntu/trusty64"
    app.vm.provision "shell", inline: "apt-get install -y python language-pack-de"
    app.vm.network :private_network, ip: "192.168.101.10"
  end

  # Ubuntu 16.04 (Xenial Xerus)
  config.vm.define "senaite-xenial" do |app|
    app.vm.hostname = "senaite"
    # https://app.vagrantup.com/ubuntu/boxes/xenial64
    app.vm.box = "ubuntu/xenial64"
    app.vm.provision "shell", inline: "apt-get install -y python language-pack-de"
    app.vm.network :private_network, ip: "192.168.101.20"
  end

  # Ubuntu 18.04 (Bionic Beaver)
  config.vm.define "senaite-bionic" do |app|
    app.vm.hostname = "senaite"
    # https://app.vagrantup.com/ubuntu/boxes/bionic64
    app.vm.box = "ubuntu/bionic64"
    app.vm.provision "shell", inline: "apt-get install -y python language-pack-de"
    app.vm.network :private_network, ip: "192.168.101.30"
  end

  # VM Settings
  config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    #   vb.gui = true
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end

end
